services:
  dev-db:
    image: postgres:13
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    networks:
      - nest
  test-db:
    image: postgres:13
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    networks:
      - nest
networks:
  nest: